GET http://localhost:3000/users

###
POST http://localhost:3000/users/register
Content-Type: application/json

{
    "name" : "miguelito",
    "role": "GUEST",
    "password": "123456"
}

###
POST http://localhost:3000/users/login
Content-Type: application/json

{
    "name" : "juanito2106",
    "password": "123456"
}